// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.2
// source: proto/payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付订单创建请求
type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                   // 订单ID
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                                   // 支付金额（分）
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`                                // 货币类型（CNY等）
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // 支付方式（ALIPAY/WECHAT）
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                          // 订单描述
	NotifyUrl     string                 `protobuf:"bytes,6,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`             // 支付结果通知地址
	ReturnUrl     string                 `protobuf:"bytes,7,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`             // 支付完成返回地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_proto_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreatePaymentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePaymentRequest) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *CreatePaymentRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

// 支付订单创建响应
type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`    // 支付ID
	PaymentUrl    string                 `protobuf:"bytes,2,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"` // 支付链接
	QrCode        string                 `protobuf:"bytes,3,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`             // 二维码链接
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                           // 支付状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_proto_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreatePaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *CreatePaymentResponse) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

func (x *CreatePaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 支付状态查询请求
type QueryPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"` // 支付ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentStatusRequest) Reset() {
	*x = QueryPaymentStatusRequest{}
	mi := &file_proto_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentStatusRequest) ProtoMessage() {}

func (x *QueryPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*QueryPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{2}
}

func (x *QueryPaymentStatusRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

// 支付状态查询响应
type QueryPaymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`             // 支付ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                    // 支付状态
	PaidAmount    int64                  `protobuf:"varint,3,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`         // 实付金额
	PaidTime      string                 `protobuf:"bytes,4,opt,name=paid_time,json=paidTime,proto3" json:"paid_time,omitempty"`                // 支付时间
	TransactionId string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 支付平台交易号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentStatusResponse) Reset() {
	*x = QueryPaymentStatusResponse{}
	mi := &file_proto_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentStatusResponse) ProtoMessage() {}

func (x *QueryPaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*QueryPaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{3}
}

func (x *QueryPaymentStatusResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *QueryPaymentStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryPaymentStatusResponse) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *QueryPaymentStatusResponse) GetPaidTime() string {
	if x != nil {
		return x.PaidTime
	}
	return ""
}

func (x *QueryPaymentStatusResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// 支付回调请求
type PaymentCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`             // 支付ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                    // 支付状态
	PaidAmount    int64                  `protobuf:"varint,3,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`         // 实付金额
	PaidTime      string                 `protobuf:"bytes,4,opt,name=paid_time,json=paidTime,proto3" json:"paid_time,omitempty"`                // 支付时间
	TransactionId string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 支付平台交易号
	Sign          string                 `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`                                        // 签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCallbackRequest) Reset() {
	*x = PaymentCallbackRequest{}
	mi := &file_proto_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCallbackRequest) ProtoMessage() {}

func (x *PaymentCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCallbackRequest.ProtoReflect.Descriptor instead.
func (*PaymentCallbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentCallbackRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentCallbackRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentCallbackRequest) GetPaidAmount() int64 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

func (x *PaymentCallbackRequest) GetPaidTime() string {
	if x != nil {
		return x.PaidTime
	}
	return ""
}

func (x *PaymentCallbackRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentCallbackRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

// 支付回调响应
type PaymentCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 处理结果
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 处理消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCallbackResponse) Reset() {
	*x = PaymentCallbackResponse{}
	mi := &file_proto_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCallbackResponse) ProtoMessage() {}

func (x *PaymentCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCallbackResponse.ProtoReflect.Descriptor instead.
func (*PaymentCallbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentCallbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaymentCallbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 取消支付请求
type CancelPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"` // 支付ID
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                        // 取消原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentRequest) Reset() {
	*x = CancelPaymentRequest{}
	mi := &file_proto_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentRequest) ProtoMessage() {}

func (x *CancelPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentRequest.ProtoReflect.Descriptor instead.
func (*CancelPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{6}
}

func (x *CancelPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CancelPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 取消支付响应
type CancelPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 取消结果
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 处理消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentResponse) Reset() {
	*x = CancelPaymentResponse{}
	mi := &file_proto_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentResponse) ProtoMessage() {}

func (x *CancelPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentResponse.ProtoReflect.Descriptor instead.
func (*CancelPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{7}
}

func (x *CancelPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取支付详情请求
type GetPaymentDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"` // 支付ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentDetailRequest) Reset() {
	*x = GetPaymentDetailRequest{}
	mi := &file_proto_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentDetailRequest) ProtoMessage() {}

func (x *GetPaymentDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentDetailRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentDetailRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

// 获取支付详情响应
type GetPaymentDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *PaymentDetail         `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"` // 支付详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentDetailResponse) Reset() {
	*x = GetPaymentDetailResponse{}
	mi := &file_proto_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentDetailResponse) ProtoMessage() {}

func (x *GetPaymentDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentDetailResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{9}
}

func (x *GetPaymentDetailResponse) GetPayment() *PaymentDetail {
	if x != nil {
		return x.Payment
	}
	return nil
}

// 支付详情
type PaymentDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`             // 支付ID
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                   // 订单ID
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                                   // 支付金额
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`                                // 货币类型
	PaymentMethod string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // 支付方式
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                    // 支付状态
	CreatedTime   string                 `protobuf:"bytes,7,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`       // 创建时间
	PaidTime      string                 `protobuf:"bytes,8,opt,name=paid_time,json=paidTime,proto3" json:"paid_time,omitempty"`                // 支付时间
	TransactionId string                 `protobuf:"bytes,9,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 支付平台交易号
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`                         // 订单描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentDetail) Reset() {
	*x = PaymentDetail{}
	mi := &file_proto_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentDetail) ProtoMessage() {}

func (x *PaymentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentDetail.ProtoReflect.Descriptor instead.
func (*PaymentDetail) Descriptor() ([]byte, []int) {
	return file_proto_payment_proto_rawDescGZIP(), []int{10}
}

func (x *PaymentDetail) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentDetail) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentDetail) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentDetail) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentDetail) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PaymentDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentDetail) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *PaymentDetail) GetPaidTime() string {
	if x != nil {
		return x.PaidTime
	}
	return ""
}

func (x *PaymentDetail) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_payment_proto protoreflect.FileDescriptor

const file_proto_payment_proto_rawDesc = "" +
	"\n" +
	"\x13proto/payment.proto\x12\tpaymentpb\"\xec\x01\n" +
	"\x14CreatePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x06 \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\a \x01(\tR\treturnUrl\"\x88\x01\n" +
	"\x15CreatePaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1f\n" +
	"\vpayment_url\x18\x02 \x01(\tR\n" +
	"paymentUrl\x12\x17\n" +
	"\aqr_code\x18\x03 \x01(\tR\x06qrCode\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\":\n" +
	"\x19QueryPaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"\xb8\x01\n" +
	"\x1aQueryPaymentStatusResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vpaid_amount\x18\x03 \x01(\x03R\n" +
	"paidAmount\x12\x1b\n" +
	"\tpaid_time\x18\x04 \x01(\tR\bpaidTime\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\"\xc8\x01\n" +
	"\x16PaymentCallbackRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vpaid_amount\x18\x03 \x01(\x03R\n" +
	"paidAmount\x12\x1b\n" +
	"\tpaid_time\x18\x04 \x01(\tR\bpaidTime\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04sign\x18\x06 \x01(\tR\x04sign\"M\n" +
	"\x17PaymentCallbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x14CancelPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"K\n" +
	"\x15CancelPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\x17GetPaymentDetailRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"N\n" +
	"\x18GetPaymentDetailResponse\x122\n" +
	"\apayment\x18\x01 \x01(\v2\x18.paymentpb.PaymentDetailR\apayment\"\xc5\x02\n" +
	"\rPaymentDetail\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12!\n" +
	"\fcreated_time\x18\a \x01(\tR\vcreatedTime\x12\x1b\n" +
	"\tpaid_time\x18\b \x01(\tR\bpaidTime\x12%\n" +
	"\x0etransaction_id\x18\t \x01(\tR\rtransactionId\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription2\xe2\x03\n" +
	"\x0ePaymentService\x12T\n" +
	"\rCreatePayment\x12\x1f.paymentpb.CreatePaymentRequest\x1a .paymentpb.CreatePaymentResponse\"\x00\x12c\n" +
	"\x12QueryPaymentStatus\x12$.paymentpb.QueryPaymentStatusRequest\x1a%.paymentpb.QueryPaymentStatusResponse\"\x00\x12`\n" +
	"\x15HandlePaymentCallback\x12!.paymentpb.PaymentCallbackRequest\x1a\".paymentpb.PaymentCallbackResponse\"\x00\x12T\n" +
	"\rCancelPayment\x12\x1f.paymentpb.CancelPaymentRequest\x1a .paymentpb.CancelPaymentResponse\"\x00\x12]\n" +
	"\x10GetPaymentDetail\x12\".paymentpb.GetPaymentDetailRequest\x1a#.paymentpb.GetPaymentDetailResponse\"\x00B\x1bZ\x19shortLink/proto/paymentpbb\x06proto3"

var (
	file_proto_payment_proto_rawDescOnce sync.Once
	file_proto_payment_proto_rawDescData []byte
)

func file_proto_payment_proto_rawDescGZIP() []byte {
	file_proto_payment_proto_rawDescOnce.Do(func() {
		file_proto_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_proto_rawDesc), len(file_proto_payment_proto_rawDesc)))
	})
	return file_proto_payment_proto_rawDescData
}

var file_proto_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_payment_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),       // 0: paymentpb.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),      // 1: paymentpb.CreatePaymentResponse
	(*QueryPaymentStatusRequest)(nil),  // 2: paymentpb.QueryPaymentStatusRequest
	(*QueryPaymentStatusResponse)(nil), // 3: paymentpb.QueryPaymentStatusResponse
	(*PaymentCallbackRequest)(nil),     // 4: paymentpb.PaymentCallbackRequest
	(*PaymentCallbackResponse)(nil),    // 5: paymentpb.PaymentCallbackResponse
	(*CancelPaymentRequest)(nil),       // 6: paymentpb.CancelPaymentRequest
	(*CancelPaymentResponse)(nil),      // 7: paymentpb.CancelPaymentResponse
	(*GetPaymentDetailRequest)(nil),    // 8: paymentpb.GetPaymentDetailRequest
	(*GetPaymentDetailResponse)(nil),   // 9: paymentpb.GetPaymentDetailResponse
	(*PaymentDetail)(nil),              // 10: paymentpb.PaymentDetail
}
var file_proto_payment_proto_depIdxs = []int32{
	10, // 0: paymentpb.GetPaymentDetailResponse.payment:type_name -> paymentpb.PaymentDetail
	0,  // 1: paymentpb.PaymentService.CreatePayment:input_type -> paymentpb.CreatePaymentRequest
	2,  // 2: paymentpb.PaymentService.QueryPaymentStatus:input_type -> paymentpb.QueryPaymentStatusRequest
	4,  // 3: paymentpb.PaymentService.HandlePaymentCallback:input_type -> paymentpb.PaymentCallbackRequest
	6,  // 4: paymentpb.PaymentService.CancelPayment:input_type -> paymentpb.CancelPaymentRequest
	8,  // 5: paymentpb.PaymentService.GetPaymentDetail:input_type -> paymentpb.GetPaymentDetailRequest
	1,  // 6: paymentpb.PaymentService.CreatePayment:output_type -> paymentpb.CreatePaymentResponse
	3,  // 7: paymentpb.PaymentService.QueryPaymentStatus:output_type -> paymentpb.QueryPaymentStatusResponse
	5,  // 8: paymentpb.PaymentService.HandlePaymentCallback:output_type -> paymentpb.PaymentCallbackResponse
	7,  // 9: paymentpb.PaymentService.CancelPayment:output_type -> paymentpb.CancelPaymentResponse
	9,  // 10: paymentpb.PaymentService.GetPaymentDetail:output_type -> paymentpb.GetPaymentDetailResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_payment_proto_init() }
func file_proto_payment_proto_init() {
	if File_proto_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_proto_rawDesc), len(file_proto_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_proto_goTypes,
		DependencyIndexes: file_proto_payment_proto_depIdxs,
		MessageInfos:      file_proto_payment_proto_msgTypes,
	}.Build()
	File_proto_payment_proto = out.File
	file_proto_payment_proto_goTypes = nil
	file_proto_payment_proto_depIdxs = nil
}
