# MySQL配置
mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "root"
  dbname: "shortlink"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10
  max_retries: 3
  dial_timeout: 5
  read_timeout: 3
  write_timeout: 3

# Kafka配置
kafka:
  host: "localhost"
  port: 9092
  brokers:
    - "localhost:9092"
  topic: "shortlink-log"

# 日志配置
logger:
  level: "info"

# 应用配置
app:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"  # debug, release, test
  jwtsecret: "your_jwt_secret"
  jwtexpire: 24  # 小时
  base62length: 6 # 短链接长度
  max_retries: 3 # 生成最大重试次数
