# 支付服务配置文件

server:
  port: 8083

database:
  host: localhost
  port: 3306
  username: root
  password: root
  dbname: shortlink

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

nacos:
  host: localhost
  port: 8848
  namespace: public
  group: DEFAULT_GROUP
  dataid: payment-service

payment:
  alipay:
    app_id: "your_alipay_app_id"
    private_key: "your_alipay_private_key"
    public_key: "your_alipay_public_key"
    notify_url: "http://your-domain.com/api/payment/alipay/notify"
    return_url: "http://your-domain.com/payment/result"
    is_sandbox: true
  wechat:
    app_id: "your_wechat_app_id"
    mch_id: "your_wechat_mch_id"
    key: "your_wechat_key"
    cert_file: "path/to/cert_file"
    key_file: "path/to/key_file"
    notify_url: "http://your-domain.com/api/payment/wechat/notify"
    is_sandbox: true

order:
  order_service:
    host: localhost
    port: 8081