// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.2
// source: proto/rbac.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 权限检查请求
type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_proto_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPermissionRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckPermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// 权限检查响应
type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasPermission bool                   `protobuf:"varint,1,opt,name=has_permission,json=hasPermission,proto3" json:"has_permission,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_proto_rbac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *CheckPermissionResponse) GetHasPermission() bool {
	if x != nil {
		return x.HasPermission
	}
	return false
}

func (x *CheckPermissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 角色信息
type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_proto_rbac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{2}
}

func (x *RoleInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 权限信息
type PermissionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionInfo) Reset() {
	*x = PermissionInfo{}
	mi := &file_proto_rbac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionInfo) ProtoMessage() {}

func (x *PermissionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionInfo.ProtoReflect.Descriptor instead.
func (*PermissionInfo) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{3}
}

func (x *PermissionInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PermissionInfo) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionInfo) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// 获取用户角色请求
type GetUserRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesRequest) Reset() {
	*x = GetUserRolesRequest{}
	mi := &file_proto_rbac_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesRequest) ProtoMessage() {}

func (x *GetUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesRequest.ProtoReflect.Descriptor instead.
func (*GetUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRolesRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取用户角色响应
type GetUserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleInfo            `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesResponse) Reset() {
	*x = GetUserRolesResponse{}
	mi := &file_proto_rbac_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesResponse) ProtoMessage() {}

func (x *GetUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesResponse.ProtoReflect.Descriptor instead.
func (*GetUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRolesResponse) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 获取角色权限请求
type GetRolePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint32                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsRequest) Reset() {
	*x = GetRolePermissionsRequest{}
	mi := &file_proto_rbac_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsRequest) ProtoMessage() {}

func (x *GetRolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{6}
}

func (x *GetRolePermissionsRequest) GetRoleId() uint32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

// 获取角色权限响应
type GetRolePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*PermissionInfo      `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsResponse) Reset() {
	*x = GetRolePermissionsResponse{}
	mi := &file_proto_rbac_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsResponse) ProtoMessage() {}

func (x *GetRolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{7}
}

func (x *GetRolePermissionsResponse) GetPermissions() []*PermissionInfo {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// 创建角色请求
type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_proto_rbac_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 创建角色响应
type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RoleInfo              `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_proto_rbac_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRoleResponse) GetRole() *RoleInfo {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *CreateRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 创建权限请求
type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_proto_rbac_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CreatePermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// 创建权限响应
type CreatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *PermissionInfo        `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_proto_rbac_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{11}
}

func (x *CreatePermissionResponse) GetPermission() *PermissionInfo {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *CreatePermissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 分配角色给用户请求
type AssignRoleToUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        uint32                 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleToUserRequest) Reset() {
	*x = AssignRoleToUserRequest{}
	mi := &file_proto_rbac_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleToUserRequest) ProtoMessage() {}

func (x *AssignRoleToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleToUserRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleToUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{12}
}

func (x *AssignRoleToUserRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssignRoleToUserRequest) GetRoleId() uint32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

// 分配角色给用户响应
type AssignRoleToUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleToUserResponse) Reset() {
	*x = AssignRoleToUserResponse{}
	mi := &file_proto_rbac_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleToUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleToUserResponse) ProtoMessage() {}

func (x *AssignRoleToUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleToUserResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleToUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{13}
}

func (x *AssignRoleToUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 分配权限给角色请求
type AssignPermissionToRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint32                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId  uint32                 `protobuf:"varint,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionToRoleRequest) Reset() {
	*x = AssignPermissionToRoleRequest{}
	mi := &file_proto_rbac_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionToRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionToRoleRequest) ProtoMessage() {}

func (x *AssignPermissionToRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionToRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignPermissionToRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{14}
}

func (x *AssignPermissionToRoleRequest) GetRoleId() uint32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AssignPermissionToRoleRequest) GetPermissionId() uint32 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

// 分配权限给角色响应
type AssignPermissionToRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionToRoleResponse) Reset() {
	*x = AssignPermissionToRoleResponse{}
	mi := &file_proto_rbac_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionToRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionToRoleResponse) ProtoMessage() {}

func (x *AssignPermissionToRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rbac_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionToRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignPermissionToRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_rbac_proto_rawDescGZIP(), []int{15}
}

func (x *AssignPermissionToRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_rbac_proto protoreflect.FileDescriptor

const file_proto_rbac_proto_rawDesc = "" +
	"\n" +
	"\x10proto/rbac.proto\x12\x04user\"e\n" +
	"\x16CheckPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"Z\n" +
	"\x17CheckPermissionResponse\x12%\n" +
	"\x0ehas_permission\x18\x01 \x01(\bR\rhasPermission\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"P\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x8a\x01\n" +
	"\x0ePermissionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\".\n" +
	"\x13GetUserRolesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"<\n" +
	"\x14GetUserRolesResponse\x12$\n" +
	"\x05roles\x18\x01 \x03(\v2\x0e.user.RoleInfoR\x05roles\"4\n" +
	"\x19GetRolePermissionsRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\rR\x06roleId\"T\n" +
	"\x1aGetRolePermissionsResponse\x126\n" +
	"\vpermissions\x18\x01 \x03(\v2\x14.user.PermissionInfoR\vpermissions\"I\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"R\n" +
	"\x12CreateRoleResponse\x12\"\n" +
	"\x04role\x18\x01 \x01(\v2\x0e.user.RoleInfoR\x04role\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x83\x01\n" +
	"\x17CreatePermissionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\"j\n" +
	"\x18CreatePermissionResponse\x124\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x14.user.PermissionInfoR\n" +
	"permission\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x17AssignRoleToUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\rR\x06roleId\"4\n" +
	"\x18AssignRoleToUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"]\n" +
	"\x1dAssignPermissionToRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\rR\x06roleId\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\rR\fpermissionId\":\n" +
	"\x1eAssignPermissionToRoleResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc9\x04\n" +
	"\vRBACService\x12N\n" +
	"\x0fCheckPermission\x12\x1c.user.CheckPermissionRequest\x1a\x1d.user.CheckPermissionResponse\x12E\n" +
	"\fGetUserRoles\x12\x19.user.GetUserRolesRequest\x1a\x1a.user.GetUserRolesResponse\x12W\n" +
	"\x12GetRolePermissions\x12\x1f.user.GetRolePermissionsRequest\x1a .user.GetRolePermissionsResponse\x12?\n" +
	"\n" +
	"CreateRole\x12\x17.user.CreateRoleRequest\x1a\x18.user.CreateRoleResponse\x12Q\n" +
	"\x10CreatePermission\x12\x1d.user.CreatePermissionRequest\x1a\x1e.user.CreatePermissionResponse\x12Q\n" +
	"\x10AssignRoleToUser\x12\x1d.user.AssignRoleToUserRequest\x1a\x1e.user.AssignRoleToUserResponse\x12c\n" +
	"\x16AssignPermissionToRole\x12#.user.AssignPermissionToRoleRequest\x1a$.user.AssignPermissionToRoleResponseB\x10Z\x0e./proto/userpbb\x06proto3"

var (
	file_proto_rbac_proto_rawDescOnce sync.Once
	file_proto_rbac_proto_rawDescData []byte
)

func file_proto_rbac_proto_rawDescGZIP() []byte {
	file_proto_rbac_proto_rawDescOnce.Do(func() {
		file_proto_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rbac_proto_rawDesc), len(file_proto_rbac_proto_rawDesc)))
	})
	return file_proto_rbac_proto_rawDescData
}

var file_proto_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_rbac_proto_goTypes = []any{
	(*CheckPermissionRequest)(nil),         // 0: user.CheckPermissionRequest
	(*CheckPermissionResponse)(nil),        // 1: user.CheckPermissionResponse
	(*RoleInfo)(nil),                       // 2: user.RoleInfo
	(*PermissionInfo)(nil),                 // 3: user.PermissionInfo
	(*GetUserRolesRequest)(nil),            // 4: user.GetUserRolesRequest
	(*GetUserRolesResponse)(nil),           // 5: user.GetUserRolesResponse
	(*GetRolePermissionsRequest)(nil),      // 6: user.GetRolePermissionsRequest
	(*GetRolePermissionsResponse)(nil),     // 7: user.GetRolePermissionsResponse
	(*CreateRoleRequest)(nil),              // 8: user.CreateRoleRequest
	(*CreateRoleResponse)(nil),             // 9: user.CreateRoleResponse
	(*CreatePermissionRequest)(nil),        // 10: user.CreatePermissionRequest
	(*CreatePermissionResponse)(nil),       // 11: user.CreatePermissionResponse
	(*AssignRoleToUserRequest)(nil),        // 12: user.AssignRoleToUserRequest
	(*AssignRoleToUserResponse)(nil),       // 13: user.AssignRoleToUserResponse
	(*AssignPermissionToRoleRequest)(nil),  // 14: user.AssignPermissionToRoleRequest
	(*AssignPermissionToRoleResponse)(nil), // 15: user.AssignPermissionToRoleResponse
}
var file_proto_rbac_proto_depIdxs = []int32{
	2,  // 0: user.GetUserRolesResponse.roles:type_name -> user.RoleInfo
	3,  // 1: user.GetRolePermissionsResponse.permissions:type_name -> user.PermissionInfo
	2,  // 2: user.CreateRoleResponse.role:type_name -> user.RoleInfo
	3,  // 3: user.CreatePermissionResponse.permission:type_name -> user.PermissionInfo
	0,  // 4: user.RBACService.CheckPermission:input_type -> user.CheckPermissionRequest
	4,  // 5: user.RBACService.GetUserRoles:input_type -> user.GetUserRolesRequest
	6,  // 6: user.RBACService.GetRolePermissions:input_type -> user.GetRolePermissionsRequest
	8,  // 7: user.RBACService.CreateRole:input_type -> user.CreateRoleRequest
	10, // 8: user.RBACService.CreatePermission:input_type -> user.CreatePermissionRequest
	12, // 9: user.RBACService.AssignRoleToUser:input_type -> user.AssignRoleToUserRequest
	14, // 10: user.RBACService.AssignPermissionToRole:input_type -> user.AssignPermissionToRoleRequest
	1,  // 11: user.RBACService.CheckPermission:output_type -> user.CheckPermissionResponse
	5,  // 12: user.RBACService.GetUserRoles:output_type -> user.GetUserRolesResponse
	7,  // 13: user.RBACService.GetRolePermissions:output_type -> user.GetRolePermissionsResponse
	9,  // 14: user.RBACService.CreateRole:output_type -> user.CreateRoleResponse
	11, // 15: user.RBACService.CreatePermission:output_type -> user.CreatePermissionResponse
	13, // 16: user.RBACService.AssignRoleToUser:output_type -> user.AssignRoleToUserResponse
	15, // 17: user.RBACService.AssignPermissionToRole:output_type -> user.AssignPermissionToRoleResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_rbac_proto_init() }
func file_proto_rbac_proto_init() {
	if File_proto_rbac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rbac_proto_rawDesc), len(file_proto_rbac_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rbac_proto_goTypes,
		DependencyIndexes: file_proto_rbac_proto_depIdxs,
		MessageInfos:      file_proto_rbac_proto_msgTypes,
	}.Build()
	File_proto_rbac_proto = out.File
	file_proto_rbac_proto_goTypes = nil
	file_proto_rbac_proto_depIdxs = nil
}
