// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.2
// source: proto/inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取产品库存请求
type GetProductInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // 产品ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductInventoryRequest) Reset() {
	*x = GetProductInventoryRequest{}
	mi := &file_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInventoryRequest) ProtoMessage() {}

func (x *GetProductInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetProductInventoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductInventoryRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// 获取产品库存响应
type GetProductInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`     // 产品ID
	TotalStock    int32                  `protobuf:"varint,2,opt,name=total_stock,json=totalStock,proto3" json:"total_stock,omitempty"` // 总库存
	Available     int32                  `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`                     // 可用库存
	Reserved      int32                  `protobuf:"varint,4,opt,name=reserved,proto3" json:"reserved,omitempty"`                       // 已预留库存
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductInventoryResponse) Reset() {
	*x = GetProductInventoryResponse{}
	mi := &file_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInventoryResponse) ProtoMessage() {}

func (x *GetProductInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetProductInventoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductInventoryResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetProductInventoryResponse) GetTotalStock() int32 {
	if x != nil {
		return x.TotalStock
	}
	return 0
}

func (x *GetProductInventoryResponse) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *GetProductInventoryResponse) GetReserved() int32 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

// 锁定库存请求
type LockInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`              // 产品ID
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                    // 订单ID
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`                                // 锁定数量
	ExpireSeconds int64                  `protobuf:"varint,4,opt,name=expire_seconds,json=expireSeconds,proto3" json:"expire_seconds,omitempty"` // 锁定过期时间（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockInventoryRequest) Reset() {
	*x = LockInventoryRequest{}
	mi := &file_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockInventoryRequest) ProtoMessage() {}

func (x *LockInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockInventoryRequest.ProtoReflect.Descriptor instead.
func (*LockInventoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *LockInventoryRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *LockInventoryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *LockInventoryRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *LockInventoryRequest) GetExpireSeconds() int64 {
	if x != nil {
		return x.ExpireSeconds
	}
	return 0
}

// 锁定库存响应
type LockInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`             // 锁定ID
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                        // 是否成功
	ExpireTime    string                 `protobuf:"bytes,3,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 过期时间
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                         // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockInventoryResponse) Reset() {
	*x = LockInventoryResponse{}
	mi := &file_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockInventoryResponse) ProtoMessage() {}

func (x *LockInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockInventoryResponse.ProtoReflect.Descriptor instead.
func (*LockInventoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *LockInventoryResponse) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *LockInventoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LockInventoryResponse) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *LockInventoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 释放库存请求
type ReleaseInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"` // 锁定ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseInventoryRequest) Reset() {
	*x = ReleaseInventoryRequest{}
	mi := &file_proto_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseInventoryRequest) ProtoMessage() {}

func (x *ReleaseInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseInventoryRequest.ProtoReflect.Descriptor instead.
func (*ReleaseInventoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseInventoryRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

// 释放库存响应
type ReleaseInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseInventoryResponse) Reset() {
	*x = ReleaseInventoryResponse{}
	mi := &file_proto_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseInventoryResponse) ProtoMessage() {}

func (x *ReleaseInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseInventoryResponse.ProtoReflect.Descriptor instead.
func (*ReleaseInventoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseInventoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseInventoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 确认库存扣减请求
type ConfirmInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"` // 锁定ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmInventoryRequest) Reset() {
	*x = ConfirmInventoryRequest{}
	mi := &file_proto_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmInventoryRequest) ProtoMessage() {}

func (x *ConfirmInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmInventoryRequest.ProtoReflect.Descriptor instead.
func (*ConfirmInventoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmInventoryRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

// 确认库存扣减响应
type ConfirmInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmInventoryResponse) Reset() {
	*x = ConfirmInventoryResponse{}
	mi := &file_proto_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmInventoryResponse) ProtoMessage() {}

func (x *ConfirmInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmInventoryResponse.ProtoReflect.Descriptor instead.
func (*ConfirmInventoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmInventoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmInventoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inventory.proto\x12\vinventorypb\";\n" +
	"\x1aGetProductInventoryRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x97\x01\n" +
	"\x1bGetProductInventoryResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vtotal_stock\x18\x02 \x01(\x05R\n" +
	"totalStock\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\x05R\tavailable\x12\x1a\n" +
	"\breserved\x18\x04 \x01(\x05R\breserved\"\x93\x01\n" +
	"\x14LockInventoryRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12%\n" +
	"\x0eexpire_seconds\x18\x04 \x01(\x03R\rexpireSeconds\"\x85\x01\n" +
	"\x15LockInventoryResponse\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vexpire_time\x18\x03 \x01(\tR\n" +
	"expireTime\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"2\n" +
	"\x17ReleaseInventoryRequest\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\"N\n" +
	"\x18ReleaseInventoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x17ConfirmInventoryRequest\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\"N\n" +
	"\x18ConfirmInventoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9e\x03\n" +
	"\x10InventoryService\x12j\n" +
	"\x13GetProductInventory\x12'.inventorypb.GetProductInventoryRequest\x1a(.inventorypb.GetProductInventoryResponse\"\x00\x12X\n" +
	"\rLockInventory\x12!.inventorypb.LockInventoryRequest\x1a\".inventorypb.LockInventoryResponse\"\x00\x12a\n" +
	"\x10ReleaseInventory\x12$.inventorypb.ReleaseInventoryRequest\x1a%.inventorypb.ReleaseInventoryResponse\"\x00\x12a\n" +
	"\x10ConfirmInventory\x12$.inventorypb.ConfirmInventoryRequest\x1a%.inventorypb.ConfirmInventoryResponse\"\x00B\x1dZ\x1bshortLink/proto/inventorypbb\x06proto3"

var (
	file_proto_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_proto_rawDescData []byte
)

func file_proto_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_proto_rawDescData
}

var file_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_inventory_proto_goTypes = []any{
	(*GetProductInventoryRequest)(nil),  // 0: inventorypb.GetProductInventoryRequest
	(*GetProductInventoryResponse)(nil), // 1: inventorypb.GetProductInventoryResponse
	(*LockInventoryRequest)(nil),        // 2: inventorypb.LockInventoryRequest
	(*LockInventoryResponse)(nil),       // 3: inventorypb.LockInventoryResponse
	(*ReleaseInventoryRequest)(nil),     // 4: inventorypb.ReleaseInventoryRequest
	(*ReleaseInventoryResponse)(nil),    // 5: inventorypb.ReleaseInventoryResponse
	(*ConfirmInventoryRequest)(nil),     // 6: inventorypb.ConfirmInventoryRequest
	(*ConfirmInventoryResponse)(nil),    // 7: inventorypb.ConfirmInventoryResponse
}
var file_proto_inventory_proto_depIdxs = []int32{
	0, // 0: inventorypb.InventoryService.GetProductInventory:input_type -> inventorypb.GetProductInventoryRequest
	2, // 1: inventorypb.InventoryService.LockInventory:input_type -> inventorypb.LockInventoryRequest
	4, // 2: inventorypb.InventoryService.ReleaseInventory:input_type -> inventorypb.ReleaseInventoryRequest
	6, // 3: inventorypb.InventoryService.ConfirmInventory:input_type -> inventorypb.ConfirmInventoryRequest
	1, // 4: inventorypb.InventoryService.GetProductInventory:output_type -> inventorypb.GetProductInventoryResponse
	3, // 5: inventorypb.InventoryService.LockInventory:output_type -> inventorypb.LockInventoryResponse
	5, // 6: inventorypb.InventoryService.ReleaseInventory:output_type -> inventorypb.ReleaseInventoryResponse
	7, // 7: inventorypb.InventoryService.ConfirmInventory:output_type -> inventorypb.ConfirmInventoryResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inventory_proto_init() }
func file_proto_inventory_proto_init() {
	if File_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_proto = out.File
	file_proto_inventory_proto_goTypes = nil
	file_proto_inventory_proto_depIdxs = nil
}
